[SIP-5-crear-servicio-base-datos-inyeccion-dependencias into main] feature: Se agrega la inyección de dependencias al proyecto base
davidbo99/food-api-service pull request #4
Opened 2023-11-05 14:02 UTC by enterpreneur369

Se agrega la inyección de dependencias al proyecto base

2023-11-07 02:42 UTC, davidbo99 requested changes
Revisar comentarios

2023-11-07 02:42 UTC, davidbo99 commented on recetasback/adapters/endpoints.py
Esta carpeta adapters a que hace referencia? Los endpoints deberian estar separados por diferentes routers dependiendo de categoria con sus correspondientes tags. Esta carpeta deberia llamarse routers o views, y contener archivos distintos de diferentes routers dependiendo de los endpoints que tenga la aplicacion.

2023-11-07 02:42 UTC, davidbo99 commented on recetasback/adapters/endpoints.py
> +    return {"status": "OK"}
podriamos definir en el nivel del modulo recetasback, una carpeta core con los enums. Esta contener un enum denominado HealthStatus y tener 3 diferentes valores: OK, DEGRADED, CRITICAL. Este status lo podria determinar basado en lo que demore una peticion basica a la base de datos a traves del servicio DB implementado.

2023-11-07 02:42 UTC, davidbo99 commented on recetasback/adapters/endpoints.py
> +    return {"status": "OK"}
No esta bien dejarlo hardcoded

2023-11-07 02:42 UTC, davidbo99 commented on recetasback/dependencies/containers.py
> +# Importa el módulo de containers y providers de la librería dependency_injector.
Estos comentarios es mejor hacerlos con docstring """ """.

2023-11-07 02:42 UTC, davidbo99 commented on recetasback/dependencies/database.py
> +class DBStatus(Enum):
Este tiene que ver con un comentario anterior. Dejemoslo como HealthStatus, para que sea general para cualquier servicio implementado. Implementar los estados que mencione en el comentario anterior y dejarlo en el directorio core.

2023-11-07 03:31 UTC, enterpreneur369 commented on recetasback/adapters/endpoints.py
Se renombra la carpeta a reouters

2023-11-07 03:32 UTC, enterpreneur369 commented on recetasback/adapters/endpoints.py
> +    return {"status": "OK"}
Se remueve este endpoint, el tema del status ya está en la clase de base de datos.

2023-11-07 03:34 UTC, enterpreneur369 commented on recetasback/dependencies/containers.py
> +# Importa el módulo de containers y providers de la librería dependency_injector.
Se reemplazan los comentarios de varias lineas por docstring.

2023-11-07 03:37 UTC, enterpreneur369 commented on recetasback/dependencies/database.py
> +class DBStatus(Enum):
Se renombra a HealthStatus

2023-11-08 02:02 UTC, davidbo99 commented on recetasback/dependencies/containers.py
> +
""" Clase container que define las dependencias de los servicios de la aplicacion. """

2023-11-08 02:46 UTC, enterpreneur369 commented on recetasback/dependencies/containers.py
> +
LIsto, ya removí los comentarios verbosos.

2023-11-08 23:10 UTC, davidbo99 approved these changes

2023-11-08 23:32 UTC, Andreagarciaescobar approved these changes

2023-11-08 23:32 UTC, merged