Primera revision de codigo de lista de recetas
davidbo99/food-api-service pull request #5
Opened 2023-11-05 16:05 UTC by Andreagarciaescobar

Profe creo que ya esta listo, cuentame si hace falta algo mas

2023-11-07 02:55 UTC, davidbo99 requested changes
Buen trabajo! Igual debemos hacer algunos cambios antes de tener esto listo

2023-11-07 02:55 UTC, davidbo99 commented on .vscode/settings.json
Este archivo .vscode deberia estar en el .gitignore

2023-11-07 02:55 UTC, davidbo99 commented on main.py
> +def create_new_recipe(recipe: RecipeCreate, db: Session = Depends(get_docstring)):#llama a la función create_recipe del módulo services para crear una nueva receta en la base de datos utilizando la s
No usen comentarios con '#', usen docstring """ """

2023-11-07 02:55 UTC, davidbo99 commented on recetasback/database/database.py
> +SQLALCHEMY_DATABASE_URL = "postgresql://user:password@localhost/dbname" #reemplazar "user", "password", "localhost", y "dbname" con los valores correctos según tu configuración de base de datos.
Utilizar variables de entorno,  no hardcodear la URL. Sincronizate con Jose para que el haga el merge primero a main, y luego implementen todo lo de base de datos con el nuevo servicio.

2023-11-07 02:55 UTC, davidbo99 commented on recetasback/models/models.py
> +class RecipeBase(BaseModel):
Esto debe ir en "/Schemas" no en models. Parece codigo copiado de chat gpt, corregir.

2023-11-07 02:55 UTC, davidbo99 commented on recetasback/services/services.py
> +def get_recipes_by_ingredients(ingredients: str, page: int = 1, limit: int = 10):
Esto porque no esta implementado? No entiendo

2023-11-07 02:55 UTC, davidbo99 commented on recetasback/services/spoonacular_api.py
> +SPOONACULAR_API_BASE_URL = "https://spoonacular.com/food-api"
Variables de entorno, deberia estar en el .envrc

2023-11-07 02:55 UTC, davidbo99 commented on recetasback/services/spoonacular_api.py
> +API_KEY = "66c2e3303dfd43ca8f52b7a8327a5158"
Jamas subir una API_KEY, esto se presenta para brechas de seguridad. Debemos reversar este commit.

2023-11-09 01:03 UTC, Andreagarciaescobar commented on .vscode/settings.json
corregido

2023-11-09 01:04 UTC, Andreagarciaescobar commented on main.py
> +def create_new_recipe(recipe: RecipeCreate, db: Session = Depends(get_docstring)):#llama a la función create_recipe del módulo services para crear una nueva receta en la base de datos utilizando la s
Corregido

2023-11-09 01:05 UTC, Andreagarciaescobar commented on recetasback/models/models.py
> +class RecipeBase(BaseModel):
Corregido

2023-11-10 23:26 UTC, enterpreneur369 commented on recetasback/database/database.py
> +SQLALCHEMY_DATABASE_URL = "postgresql://user:password@localhost/dbname" #reemplazar "user", "password", "localhost", y "dbname" con los valores correctos según tu configuración de base de datos.
Corregido

2023-11-10 23:26 UTC, enterpreneur369 commented on recetasback/services/services.py
> +def get_recipes_by_ingredients(ingredients: str, page: int = 1, limit: int = 10):
Corregido

2023-11-10 23:26 UTC, enterpreneur369 commented on recetasback/services/spoonacular_api.py
> +SPOONACULAR_API_BASE_URL = "https://spoonacular.com/food-api"
Corregido

2023-11-10 23:26 UTC, enterpreneur369 commented on recetasback/services/spoonacular_api.py
> +API_KEY = "66c2e3303dfd43ca8f52b7a8327a5158"
Corregido, reset del comit

2023-11-10 23:29 UTC, enterpreneur369 approved these changes

2023-11-11 02:05 UTC, davidbo99 approved these changes

2023-11-11 02:06 UTC, merged